version: '3'
services:
  my-data-base:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE=scd40
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db